# Generated by Django 5.1.3 on 2024-12-04 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_vote_archived_route_vote_route_delete_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='route_images/'),
        ),
        migrations.AlterField(
            model_name='route',
            name='difficulty',
            field=models.CharField(choices=[('V0', 'V0'), ('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4'), ('V5', 'V5'), ('V6', 'V6'), ('V7', 'V7'), ('V8', 'V8'), ('V9', 'V9'), ('V10', 'V10')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('route', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('route', 'user')},
        ),
    ]
