# Generated by Django 5.1.3 on 2024-12-09 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_newsletterpost_image_alter_newsletterpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
