# Generated by Django 5.1.3 on 2024-12-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_staff_member',
            new_name='staff_status',
        ),
    ]
