# Generated by Django 5.1.3 on 2024-12-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_is_staff_member_profile_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_routes',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='project.route'),
        ),
    ]
