# Generated by Django 5.1.4 on 2024-12-10 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_profile_bio_route_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='membership_start_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
