# Generated by Django 5.1.4 on 2024-12-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_route_difficulty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
